version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fullstack-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - DEBUG=True
    restart: unless-stopped
    networks:
      - fullstack-network

  frontend:
    build: ./frontend
    container_name: fullstack-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge
