from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'tasks', views.TaskViewSet, basename='task')

urlpatterns = [
    path('', include(router.urls)),
]

# URLs automatically generated by the router are:
# GET    /api/tasks/           - List all tasks (with pagination)
# POST   /api/tasks/           - Create new task
# GET    /api/tasks/{id}/      - Get specific task
# PUT    /api/tasks/{id}/      - Update complete task
# PATCH  /api/tasks/{id}/      - Update partial task
# DELETE /api/tasks/{id}/      - Delete task
# POST   /api/tasks/{id}/toggle/ - Toggle completion status
# GET    /api/tasks/completed/ - List only completed tasks
# GET    /api/tasks/pending/   - List only pending tasks
# GET    /api/tasks/stats/     - Get task statistics
