# Generated by Django 4.2.7 on 2025-08-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Task name', max_length=255)),
                ('completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Task creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Task last update timestamp')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='tasks_name_134490_idx'), models.Index(fields=['completed'], name='tasks_complet_563b30_idx'), models.Index(fields=['created_at'], name='tasks_created_db4e37_idx')],
            },
        ),
    ]
